<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="DrillingContainer" Id="{30cf670d-92da-40f3-8509-6b36eaf93e94}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK DrillingContainer EXTENDS ZCore.ObjectContainer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
  {attribute 'hide'}
  _parent : REFERENCE TO DrillingUnit;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{c0be20b2-502b-46f9-8bcb-77e1aafecf1e}">
      <Declaration><![CDATA[{ attribute 'hide' }
METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
  unit : REFERENCE TO DrillingUnit;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_parent REF= unit;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>
