<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="QualityInspectionSequenceBoot" Id="{1e0e192f-58c7-4db6-acc0-e7714497509f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK QualityInspectionSequenceBoot EXTENDS QualityInspectionSequence IMPLEMENTS ZCore.ISequence
VAR
  _step : ZCore.Step(QualityInspectionStep.BootBegin, QualityInspectionStep.BootEnd);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF OnStart(_step) THEN
  ; // init custom sequence variables here ...
END_IF

REPEAT
  LogStep();

  CASE _step.Index OF
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
    QualityInspectionStep.BootBegin:
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
      IF _step.OnEntry()
      THEN
        // initialize equipment
        _io();
        _actuator();
        _fieldbus();
        _axis();
        _unit();
      END_IF
      
      _parent._objectManager.Cyclic();      
      Assert(_parent._objectManager);
      IF _parent._objectManager.Done
      THEN
        _step.SetNext(QualityInspectionStep.BootEnd);
      END_IF

    (* -------------------------------------------------------------------------------------------------------------------------------- *)
    QualityInspectionStep.BootEnd:
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
      SetBusy(FALSE);
      
  ELSE
    Abort('sequence contains unhandled step');
  END_CASE
UNTIL _step.IsNotRepeatable() OR_ELSE NOT Busy END_REPEAT]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
