<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="QualityInspectionEquipment" Id="{b5b43338-ca3c-42ed-8546-901a8b1662f0}" SpecialFunc="None">
    <Declaration><![CDATA[/// This function block is a container for equipment that is used by this unit.
/// Equipment is grouped by its kind (actuator, axes, io, ...).
/// It extends from [ManagedObjectContainer](xref:ZCore.ManagedObjectContainer) such that the parent
/// (= the unit itself) can be passed to equipment instances.
FUNCTION_BLOCK QualityInspectionEquipment EXTENDS QualityInspectionContainer
VAR_INPUT
  Io : QualityInspectionIo(_parent);
  Actuator : QualityInspectionActuator(_parent);
  Axis : QualityInspectionAxis(_parent);
  Fieldbus : QualityInspectionFieldbus(_parent);
  Unit : QualityInspectionLinkedUnit(_parent);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
