<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="AssemblyEquipment" Id="{235fe708-257e-4e00-9ea1-45801f80422e}" SpecialFunc="None">
    <Declaration><![CDATA[/// This function block is a container for equipment that is used by this unit.
/// Equipment is grouped by its kind (actuator, axes, io, ...).
/// It extends from [ManagedObjectContainer](xref:ZCore.ManagedObjectContainer) such that the parent
/// (= the unit itself) can be passed to equipment instances.
FUNCTION_BLOCK AssemblyEquipment EXTENDS AssemblyContainer
VAR_INPUT
  Io : AssemblyIo(_parent);
  Actuator : AssemblyActuator(_parent);
  Axis : AssemblyAxis(_parent);
  Fieldbus : AssemblyFieldbus(_parent);
  Unit : AssemblyLinkedUnit(_parent);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
